name: Notify Fork

on:
  push:
    branches:
      - main

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send Dispatch Event to Fork
        run: |
          curl -X POST -H "Authorization: token ${{ secrets.PAT_TOKEN }}" \
               -H "Accept: application/vnd.github.v3+json" \
               https://api.github.com/repos/saikumar-mandaji/Auto-Deploy/dispatches \
               -d '{"event_type":"sync"}'
